const countryList = {
  "USD": "US",
  "EUR": "EU", 
  "GBP": "GB", 
  "INR": "IN", 
  "AUD": "AU", 
  "CAD": "CA", 
  "JPY": "JP", 
  "CNY": "CN", 
  "CHF": "CH", 
  "NZD": "NZ", 
  "SGD": "SG",
  "HKD": "HK",
  "SEK": "SE", 
  "NOK": "NO", 
  "DKK": "DK", 
  "ZAR": "ZA", 
  "RUB": "RU", 
  "BRL": "BR", 
  "MXN": "MX", 
  "KRW": "KR", 
};
